### ISSUE TITLE
你好，朋友，请问你这个主题可以正常使用吗？

### ISSUE THREAD

**Issue by zard-zhang** [evansuner/hexo-clover-next#1]

**Comment by evansuner** [comment]
clone之后需要npm i 一下On Oct 29, 2022, at 16:46, zard-zhang ***@***.***> wrote:﻿

**Comment by zard-zhang** [comment]
> clone之后需要npm i 一下On Oct 29, 2022, at 16:46, zard-zhang ***@***.***> wrote:﻿ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

nom i 报错了
‘’‘
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c -- node scripts/build.js
npm ERR! Building: /opt/homebrew/Cellar/node/18.10.0/bin/node /Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/opt/homebrew/Cellar/node/18.10.0/bin/node',
npm ERR! gyp verb cli   '/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.10.0 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /Users/zard/Desktop/blog/hexo-clover-next/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/18.10.0/bin/node" "/Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/zard/Desktop/blog/hexo-clover-next/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.10.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zard/.npm/_logs/2022-10-29T09_41_22_337Z-debug-0.log
‘’‘

**Comment by zard-zhang** [comment]
npm I 报错了

**Comment by evansuner** [comment]
node需要14版本 并且外网 因为hexo-renderer-sass使用国内的镜像会失败On Oct 29, 2022, at 17:44, zard-zhang ***@***.***> wrote:﻿
npm I 报错了

**Comment by zard-zhang** [comment]
我挂了梯子，也降了版本，安装插件还是报错，你可以正常使用吗？

**Comment by evansuner** [comment]
我可以正常使用，你让我看下报错信息On Oct 30, 2022, at 21:18, zard-zhang ***@***.***> wrote:﻿
我挂了梯子，也降了版本，安装插件还是报错，你可以正常使用吗？

**Comment by evansuner** [comment]
对了过了梯子之后npm不要使用cpm和阿里镜像，需要恢复成官网镜像On Oct 30, 2022, at 21:18, zard-zhang ***@***.***> wrote:﻿
我挂了梯子，也降了版本，安装插件还是报错，你可以正常使用吗？

**Comment by evansuner** [comment]
> node需要14版本 并且外网 因为hexo-renderer-sass使用国内的镜像会失败On Oct 29, 2022, at 17:44, zard-zhang ***@***.***> wrote:﻿ npm I 报错了 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

我在 release 发布了一个 npm install 之后的版本, 你可以试试, 启动看项目的 readme
